spring.application.name=Notificacao
server.port=8080
spring.datasource.url=${JDBC_URL_NOTIFICACAO:jdbc:postgresql://localhost:5433/notificacao}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL:true}

api.security.token.secret=${JWT_SECRET:bananaSegredo}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5673}
spring.rabbitmq.username=${RABBITMQ_DEFAULT_PASS:guest}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS:guest}
broker.queue.notificacao.queue=${QUEUE_EMAIL_NAME:notificacao.v1.notificacao-enviar}
broker.queue.notificacao.exchange=${EXCHANGE_EMAIL_NAME:notificacao.email}

spring.task.scheduling.fixedrate=${PUBLISHER_NOTIFICACAO:60000}
